package com.taxipro.ui.theme

import androidx.compose.runtime.compositionLocalOf
import com.taxipro.data.db.AppSettings

data class AppStrings(
    // Navigation
    val navRide: String,
    val navStats: String,
    val navSettings: String,
    val navMore: String,
    // Shift banner
    val shiftNoneTitle: String,
    val shiftNoneWarning: String,
    val shiftStartBtn: String,
    val shiftActiveLabel: String,
    val shiftEndBtn: String,
    // Time units (used in shift duration display)
    val hoursAbbr: String,
    val minAbbr: String,
    // Active ride - fare card
    val currentFare: String,
    val statusWaiting: String,
    val statusDriving: String,
    val inclAdjustment: String,
    // Metric cards
    val waitLabel: String,
    val secondsMin: String,
    val speedLabel: String,
    val distanceLabel: String,
    // Fare adjustment
    val fareAdjTitle: String,
    val resetBtn: String,
    val fareAdjHint: String,
    // Tariff
    val tariffLabel: String,
    // Start button
    val startGpsRide: String,
    // Controls
    val pauseBtn: String,
    val resumeBtn: String,
    val endBtn: String,
    // End ride dialog
    val endOfRide: String,
    val rideSummary: String,
    val distanceField: String,
    val durationField: String,
    val waitTimeField: String,
    val paymentMethod: String,
    val cash: String,
    val card: String,
    val tipLabel: String,
    val saveBtn: String,
    val cancelBtn: String,
    // No tariff
    val noTariffTitle: String,
    val noTariffMsg: String,
    // No shift dialog
    val noShiftDialogTitle: String,
    val noShiftDialogMsg: String,
    val yesContinue: String,
    val noGoBack: String,
    // Dashboard
    val goodDay: String,
    val todayLabel: String,
    val ridesLabel: String,
    val monthlyRevenue: String,
    val avgRide: String,
    val perRide: String,
    val tipsToday: String,
    val received: String,
    val netProfit: String,
    val afterCosts: String,
    val recentRides: String,
    val noRidesYet: String,
    val ridePrefix: String,
    val tipBadge: String,
    // Statistics
    val statistics: String,
    val weekLabel: String,
    val monthLabel: String,
    val allLabel: String,
    val totalRevenue: String,
    val totalKm: String,
    val avgPerHour: String,
    val avgShift: String,
    val traveled: String,
    val revenuePerHour: String,
    val shiftsLabel: String,
    val noShiftSub: String,
    val choosePeriod: String,
    val noData: String,
    val trendsTitle: String,
    val byDay: String,
    val byHour: String,
    val byMonth: String,
    val revenueByDow: String,
    val rideCountByDay: String,
    val revenueByHour: String,
    val bestHourColon: String,
    val revenueByMonth: String,
    val kpiTitle: String,
    val revenuePerKm: String,
    val totalTips: String,
    val totalWaitKpi: String,
    val workTime: String,
    val bestDay: String,
    val peakHour: String,
    val rideCount: String,
    val efficiencyTitle: String,
    val timeWithClient: String,
    val waitEfficiency: String,
    val topRoutesTitle: String,
    val timesLabel: String,
    val breakdownTitle: String,
    val grossRevenue: String,
    val fuelBreakdown: String,
    val taxBreakdown: String,
    val dayLabels: List<String>,
    val monthLabels: List<String>,
    // Settings
    val settingsTitle: String,
    val languageSection: String,
    val languageComingSoon: String,
    val currencySection: String,
    val exchangeRatesNote: String,
    val distanceSection: String,
    val kilometres: String,
    val miles: String,
    val tariffsSection: String,
    val noTariffs: String,
    val manualLabel: String,
    val autoLabel: String,
    val addTariff: String,
    val expensesSection: String,
    val taxInsurance: String,
    val fuelPer: String,
    val gpsSection: String,
    val waitThreshold: String,
    val waitThresholdHint: String,
    val updateInterval: String,
    val updateIntervalHint: String,
    val advancedSection: String,
    val advancedSectionSub: String,
    val costsLabel: String,
    val profitPreviewTitle: String,
    val profitPreviewNoTariff: String,
    val profitPreviewSub: String,
    val fuelLabel: String,
    val shift8hTitle: String,
    val shift8hAvgPerHour: String,
    val shift8hGross: String,
    val shift8hNet: String,
    val notEnoughDataLabel: String,
    val notEnoughDataSub: String,
    val per100GrossTitle: String,
    val saveChanges: String,
    val newTariff: String,
    val editTariffLabel: String,
    val tariffName: String,
    val nameRequired: String,
    val pricingLabel: String,
    val startFeeLabel: String,
    val perMinWait: String,
    val hourlyRateLabel: String,
    val autoActivate: String,
    val autoActivateSub: String,
    val fromLabel: String,
    val toLabel: String,
    val saveLabel: String,
    // History
    val historyTitle: String,
    val showLabel: String,
    val noRides: String,
    val noRoute: String,
    val startMarker: String,
    val endMarker: String,
    // More menu
    val moreTitle: String,
    val moreSub: String,
    val rideHistoryTitle: String,
    val rideHistorySub: String,
    val shiftHistoryTitle: String,
    val shiftHistorySub: String,
    val calculatorLabel: String,
    val calculatorSub: String,
    val mapLabel: String,
    val mapSub: String,
    // Shift history
    val shiftHistoryScreen: String,
    val shiftsRecorded: String,
    val noShifts: String,
    val shiftNum: String,
    val activeLabel: String,
    val avgRideLabel: String,
    val tipsLabel: String,
    val waitLabelShort: String,
    val profitLabel: String,
    val noRidesInShift: String,
    val tipBadgeShort: String,
    // Shift summary
    val shiftCompleted: String,
    val ridesCompleted: String,
    val completedLabel: String,
    val kilometersLabel: String,
    val withClients: String,
    val avgRidePerRide: String,
    val totalWaitLabel: String,
    val noMovement: String,
    val financialBreakdown: String,
    val ridesInShift: String,
    val doneBtn: String,
    // Calculator
    val defaultLabel: String,
    val fromPointLabel: String,
    val toPointLabel: String,
    val swapLabel: String,
    val calculating: String,
    val calculateRoutes: String,
    val timeLabel: String,
    val totalLabel: String,
    val savedAsRide: String,
    val saveAsRide: String,
    val secAbbr: String,
    val perKmLabel: String,
    val perMinLabel: String,
    val myLocationLabel: String,
    val enterFromTo: String,
    val noRouteFound: String,
    val addressNotFound: String,
    val directionsApiError: String,
    val networkError: String,
    val routesSingle: String,
    val routesPlural: String,
    // Ride history
    val waitSuffix: String,
    // Currency fetch
    val refreshRates: String,
    val fetchingRates: String,
    val ratesFetched: String,
    val ratesFailed: String,
)

// ── English ──────────────────────────────────────────────────────
val EnStrings = AppStrings(
    navRide = "Ride", navStats = "Stats", navSettings = "Settings", navMore = "More",
    shiftNoneTitle = "No active shift",
    shiftNoneWarning = "Tracking shifts helps you see daily earnings, compare performance and keep accurate records.",
    shiftStartBtn = "Start shift",
    shiftActiveLabel = "Shift #%d active",
    shiftEndBtn = "End shift",
    hoursAbbr = "h", minAbbr = "min",
    currentFare = "CURRENT FARE",
    statusWaiting = "⏸  WAITING", statusDriving = "▶  DRIVING",
    inclAdjustment = "incl. adjustment",
    waitLabel = "WAIT", secondsMin = "seconds / min", speedLabel = "SPEED", distanceLabel = "DISTANCE",
    fareAdjTitle = "FARE ADJUSTMENT", resetBtn = "Reset",
    fareAdjHint = "Tap to add or remove from the fare (not a tip)",
    tariffLabel = "TARIFF",
    startGpsRide = "START GPS RIDE",
    pauseBtn = "Pause", resumeBtn = "Resume", endBtn = "END",
    endOfRide = "End of ride", rideSummary = "RIDE SUMMARY",
    distanceField = "Distance", durationField = "Duration", waitTimeField = "Wait time",
    paymentMethod = "Payment method", cash = "💵 Cash", card = "💳 Card",
    tipLabel = "Tip", saveBtn = "SAVE", cancelBtn = "Cancel",
    noTariffTitle = "No tariff selected",
    noTariffMsg = "Please add a tariff in Settings before starting a ride.",
    noShiftDialogTitle = "No active shift",
    noShiftDialogMsg = "You have no active shift. The ride will be saved in overall statistics but will not count towards a shift.\n\nDo you want to continue?",
    yesContinue = "Yes, continue", noGoBack = "No, go back",
    goodDay = "Good day, driver! 🚕",
    todayLabel = "Today", ridesLabel = "Rides", monthlyRevenue = "Monthly revenue",
    avgRide = "Avg ride", perRide = "per ride", tipsToday = "Tips today",
    received = "received", netProfit = "Net profit", afterCosts = "after costs",
    recentRides = "Recent rides",
    noRidesYet = "No rides yet.\nTap 'Ride' to start!",
    ridePrefix = "Ride #", tipBadge = "tip",
    statistics = "Statistics", weekLabel = "Week", monthLabel = "Month", allLabel = "All",
    totalRevenue = "Total revenue", totalKm = "Total km",
    avgPerHour = "Avg/hour", avgShift = "Avg shift",
    traveled = "traveled", revenuePerHour = "revenue/hour",
    shiftsLabel = "shifts", noShiftSub = "no shift",
    choosePeriod = "Choose period", noData = "No data for the selected period.",
    trendsTitle = "📈 Trends", byDay = "By day", byHour = "By hour", byMonth = "By month",
    revenueByDow = "Revenue by day of week", rideCountByDay = "Ride count by day",
    revenueByHour = "Revenue by hour of day", bestHourColon = "Best hour:",
    revenueByMonth = "Revenue by month",
    kpiTitle = "📊 Key indicators", revenuePerKm = "Revenue per km",
    totalTips = "Total tips", totalWaitKpi = "Total wait", workTime = "Work time",
    bestDay = "Best day", peakHour = "Peak hour", rideCount = "Ride count",
    efficiencyTitle = "⚡ Efficiency", timeWithClient = "Time with client",
    waitEfficiency = "Wait time", topRoutesTitle = "🗺 Top routes", timesLabel = "times",
    breakdownTitle = "💸 Breakdown (approx.)", grossRevenue = "Gross revenue",
    fuelBreakdown = "Fuel (~0.18/km)", taxBreakdown = "Tax (15%)",
    dayLabels = listOf("Mon","Tue","Wed","Thu","Fri","Sat","Sun"),
    monthLabels = listOf("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"),
    settingsTitle = "Settings", languageSection = "🌐  Language",
    languageComingSoon = "Coming soon",
    currencySection = "💱  Currency",
    exchangeRatesNote = "Exchange rates vs EUR  (update manually every 2 weeks)",
    distanceSection = "📍  Distance unit", kilometres = "Kilometres", miles = "Miles",
    tariffsSection = "📋  Tariffs", noTariffs = "No tariffs yet.",
    manualLabel = "Manual", autoLabel = "Auto", addTariff = "Add Tariff",
    expensesSection = "💸  Expenses", taxInsurance = "Tax & insurance", fuelPer = "Fuel per",
    gpsSection = "📡  GPS", waitThreshold = "Wait threshold",
    waitThresholdHint = "Speed below which wait time is counted",
    updateInterval = "Update interval",
    updateIntervalHint = "Min 1000ms (Android limit). 1000 = max precision",
    advancedSection = "⚙️  Advanced settings",
    advancedSectionSub = "GPS interval and other options",
    costsLabel = "COSTS",
    profitPreviewTitle = "💡 Profit preview",
    profitPreviewNoTariff = "Select a tariff to see profit estimate.",
    profitPreviewSub = "Estimated per 100 km (excl. wait)",
    fuelLabel = "Fuel",
    shift8hTitle = "📈 8-hour shift estimate",
    shift8hAvgPerHour = "Avg / hour",
    shift8hGross = "Gross (8h)",
    shift8hNet = "Net (8h)",
    notEnoughDataLabel = "Not enough data yet",
    notEnoughDataSub = "Complete at least 1 shift to see the 8h estimate.",
    per100GrossTitle = "💰 Per 100 gross",
    saveChanges = "Save Changes", newTariff = "New Tariff", editTariffLabel = "Edit Tariff",
    tariffName = "Tariff name", nameRequired = "Name is required",
    pricingLabel = "PRICING", startFeeLabel = "Start fee", perMinWait = "Per min wait",
    hourlyRateLabel = "Hourly rate", autoActivate = "Auto-activate",
    autoActivateSub = "Switches on at a specific hour",
    fromLabel = "From", toLabel = "To", saveLabel = "Save",
    historyTitle = "History", showLabel = "Show:", noRides = "No rides for the selected period.",
    noRoute = "No route recorded for this ride.", startMarker = "Start", endMarker = "End",
    moreTitle = "More", moreSub = "Additional features",
    rideHistoryTitle = "Ride History", rideHistorySub = "View all rides",
    shiftHistoryTitle = "Shift History", shiftHistorySub = "View by work shifts",
    calculatorLabel = "Calculator", calculatorSub = "Calculate fare by route",
    mapLabel = "Map", mapSub = "Current position and route",
    shiftHistoryScreen = "Shift History", shiftsRecorded = "%d shifts recorded",
    noShifts = "No completed shifts yet.", shiftNum = "Shift #%d", activeLabel = "ACTIVE",
    avgRideLabel = "Avg ride", tipsLabel = "Tips", waitLabelShort = "Wait",
    profitLabel = "Profit", noRidesInShift = "No rides in this shift.", tipBadgeShort = "tip",
    shiftCompleted = "Shift #%d complete", ridesCompleted = "Rides", completedLabel = "completed",
    kilometersLabel = "Kilometres", withClients = "with clients", avgRidePerRide = "per ride",
    totalWaitLabel = "Total wait", noMovement = "no movement",
    financialBreakdown = "💸 Financial breakdown", ridesInShift = "🚖 Rides in this shift",
    doneBtn = "Done",
    defaultLabel = "Default", fromPointLabel = "Start point", toPointLabel = "End point",
    swapLabel = "Swap", calculating = "Calculating...", calculateRoutes = "Calculate routes",
    timeLabel = "Time", totalLabel = "Total",
    savedAsRide = "Saved as ride", saveAsRide = "Save as ride",
    secAbbr = "s", perKmLabel = "/km", perMinLabel = "/min",
    myLocationLabel = "My location",
    enterFromTo = "Enter a start and end point",
    noRouteFound = "No route found",
    addressNotFound = "Address not found",
    directionsApiError = "Directions API is not enabled for this key",
    networkError = "Network error:",
    routesSingle = "route", routesPlural = "routes",
    waitSuffix = "min wait",
    refreshRates = "🔄 Refresh rates", fetchingRates = "Fetching...",
    ratesFetched = "✓ Rates updated", ratesFailed = "Failed to fetch rates",
)

// ── Bulgarian ─────────────────────────────────────────────────────
val BgStrings = AppStrings(
    navRide = "Курс", navStats = "Статист.", navSettings = "Настройки", navMore = "Още",
    shiftNoneTitle = "Няма активна смяна",
    shiftNoneWarning = "Проследяването на смени ви помага да виждате приходите за работен ден, да сравнявате представянето си и да водите точни записи.",
    shiftStartBtn = "Започни смяна",
    shiftActiveLabel = "Смяна #%d активна",
    shiftEndBtn = "Приключи",
    hoursAbbr = "ч", minAbbr = "мин",
    currentFare = "ТЕКУЩА ЦЕНА",
    statusWaiting = "⏸  ИЗЧАКВАНЕ", statusDriving = "▶  ШОФИРАНЕ",
    inclAdjustment = "вкл. корекция",
    waitLabel = "ПРЕСТОЙ", secondsMin = "секунди / мин", speedLabel = "СКОРОСТ", distanceLabel = "РАЗСТОЯНИЕ",
    fareAdjTitle = "КОРЕКЦИЯ НА ЦЕНА", resetBtn = "Нулиране",
    fareAdjHint = "Натисни за добавяне или премахване от цената (не е бакшиш)",
    tariffLabel = "ТАРИФА",
    startGpsRide = "СТАРТИРАЙ GPS КУРС",
    pauseBtn = "Пауза", resumeBtn = "Продължи", endBtn = "КРАЙ",
    endOfRide = "Край на курс", rideSummary = "ОБОБЩЕНИЕ НА КУРС",
    distanceField = "Разстояние", durationField = "Продължителност", waitTimeField = "Престой",
    paymentMethod = "Начин на плащане", cash = "💵 В брой", card = "💳 Карта",
    tipLabel = "Бакшиш", saveBtn = "ЗАПАЗИ", cancelBtn = "Отказ",
    noTariffTitle = "Нямате избрана тарифа",
    noTariffMsg = "Моля добавете тарифа в Настройки преди да започнете курс.",
    noShiftDialogTitle = "Няма активна смяна",
    noShiftDialogMsg = "Нямате активна смяна. Курсът ще бъде записан в общата статистика, но няма да се счита към смяна.\n\nИскате ли да продължите?",
    yesContinue = "Да, продължи", noGoBack = "Не, върни се",
    goodDay = "Добър ден, шофьор! 🚕",
    todayLabel = "Днес", ridesLabel = "Курса", monthlyRevenue = "Месечен приход",
    avgRide = "Среден курс", perRide = "за курс", tipsToday = "Бакшиши днес",
    received = "получени", netProfit = "Чиста печалба", afterCosts = "след разходи",
    recentRides = "Последни курсове",
    noRidesYet = "Все още няма курсове.\nНатисни 'Курс' за да започнеш!",
    ridePrefix = "Курс #", tipBadge = "бакш.",
    statistics = "Статистики", weekLabel = "Седмица", monthLabel = "Месец", allLabel = "Всички",
    totalRevenue = "Общо приходи", totalKm = "Общо км",
    avgPerHour = "Сред. на час", avgShift = "Сред. смяна",
    traveled = "изминати", revenuePerHour = "приход/час",
    shiftsLabel = "смени", noShiftSub = "без смяна",
    choosePeriod = "Избери период", noData = "Няма данни за избрания период.",
    trendsTitle = "📈 Тенденции", byDay = "По ден", byHour = "По час", byMonth = "По месец",
    revenueByDow = "Приход по ден от седмицата", rideCountByDay = "Брой курсове по ден",
    revenueByHour = "Приход по час от деня", bestHourColon = "Най-добър час:",
    revenueByMonth = "Приход по месец",
    kpiTitle = "📊 Ключови показатели", revenuePerKm = "Приход на км",
    totalTips = "Общо бакшиши", totalWaitKpi = "Общо престой", workTime = "Работно време",
    bestDay = "Най-добър ден", peakHour = "Пик час", rideCount = "Брой курсове",
    efficiencyTitle = "⚡ Ефективност", timeWithClient = "Време с клиент",
    waitEfficiency = "Престой", topRoutesTitle = "🗺 Топ маршрути", timesLabel = "пъти",
    breakdownTitle = "💸 Разбивка (приблизителна)", grossRevenue = "Брутен приход",
    fuelBreakdown = "Гориво (~0.18/км)", taxBreakdown = "Данъци (15%)",
    dayLabels = listOf("Пн","Вт","Ср","Чт","Пт","Сб","Нд"),
    monthLabels = listOf("Ян","Фев","Мар","Апр","Май","Юн","Юл","Авг","Сеп","Окт","Ное","Дек"),
    settingsTitle = "Настройки", languageSection = "🌐  Език",
    languageComingSoon = "Очаквайте скоро",
    currencySection = "💱  Валута",
    exchangeRatesNote = "Обменни курсове спрямо EUR (актуализирайте ръчно на всеки 2 седмици)",
    distanceSection = "📍  Мерна единица", kilometres = "Километри", miles = "Мили",
    tariffsSection = "📋  Тарифи", noTariffs = "Все още няма тарифи.",
    manualLabel = "Ръчна", autoLabel = "Авто", addTariff = "Добави тарифа",
    expensesSection = "💸  Разходи", taxInsurance = "Данъци и застраховки", fuelPer = "Гориво на",
    gpsSection = "📡  GPS", waitThreshold = "Праг на изчакване",
    waitThresholdHint = "Скорост, под която се отчита престой",
    updateInterval = "Интервал на обновяване",
    updateIntervalHint = "Мин 1000мс (лимит на Android). 1000 = макс точност",
    advancedSection = "⚙️  Разширени настройки",
    advancedSectionSub = "GPS интервал и други опции",
    costsLabel = "РАЗХОДИ",
    profitPreviewTitle = "💡 Прогноза за печалба",
    profitPreviewNoTariff = "Избери тарифа за прогноза на печалбата.",
    profitPreviewSub = "Приблизително на 100 км (без престой)",
    fuelLabel = "Гориво",
    shift8hTitle = "📈 Прогноза за 8-часова смяна",
    shift8hAvgPerHour = "Сред. на час",
    shift8hGross = "Брутно (8ч)",
    shift8hNet = "Чисто (8ч)",
    notEnoughDataLabel = "Недостатъчно данни",
    notEnoughDataSub = "Завърши поне 1 смяна за 8-часова прогноза.",
    per100GrossTitle = "💰 На 100 оборот",
    saveChanges = "Запази промените", newTariff = "Нова тарифа", editTariffLabel = "Редактирай тарифа",
    tariffName = "Ime на тарифата", nameRequired = "Името е задължително",
    pricingLabel = "ЦЕНООБРАЗУВАНЕ", startFeeLabel = "Начална такса", perMinWait = "На мин престой",
    hourlyRateLabel = "Почасова ставка", autoActivate = "Авто-активиране",
    autoActivateSub = "Включва се в определен час",
    fromLabel = "От", toLabel = "До", saveLabel = "Запази",
    historyTitle = "История", showLabel = "Покажи:", noRides = "Няма курсове за избрания период.",
    noRoute = "Няма запазен маршрут за този курс.", startMarker = "Начало", endMarker = "Край",
    moreTitle = "Още", moreSub = "Допълнителни функции",
    rideHistoryTitle = "История на курсове", rideHistorySub = "Преглед на всички курсове",
    shiftHistoryTitle = "История на смени", shiftHistorySub = "Преглед по работни смени",
    calculatorLabel = "Калкулатор", calculatorSub = "Изчисли цена по маршрут",
    mapLabel = "Карта", mapSub = "Текуща позиция и маршрут",
    shiftHistoryScreen = "История на смени", shiftsRecorded = "%d смени записани",
    noShifts = "Все още няма завършени смени.", shiftNum = "Смяна #%d", activeLabel = "АКТИВНА",
    avgRideLabel = "Среден курс", tipsLabel = "Бакшиши", waitLabelShort = "Престой",
    profitLabel = "Печалба", noRidesInShift = "Няма курсове в тази смяна.", tipBadgeShort = "бакш.",
    shiftCompleted = "Смяна #%d завърши", ridesCompleted = "Курсове", completedLabel = "завършени",
    kilometersLabel = "Километри", withClients = "с клиенти", avgRidePerRide = "на курс",
    totalWaitLabel = "Общо престой", noMovement = "без движение",
    financialBreakdown = "💸 Финансова разбивка", ridesInShift = "🚖 Курсове в тази смяна",
    doneBtn = "Готово",
    defaultLabel = "По подразб.", fromPointLabel = "Начална точка", toPointLabel = "Крайна точка",
    swapLabel = "Размени", calculating = "Изчисляване...", calculateRoutes = "Изчисли маршрути",
    timeLabel = "Време", totalLabel = "Общо",
    savedAsRide = "Запазен като курс", saveAsRide = "Запази като курс",
    secAbbr = "сек", perKmLabel = "/km", perMinLabel = "/мин",
    myLocationLabel = "Моето местоположение",
    enterFromTo = "Въведи начална и крайна точка",
    noRouteFound = "Не е намерен маршрут",
    addressNotFound = "Адресът не е намерен",
    directionsApiError = "Directions API не е активиран за този ключ",
    networkError = "Мрежова грешка:",
    routesSingle = "маршрут", routesPlural = "маршрута",
    waitSuffix = "мин престой",
    refreshRates = "🔄 Обнови курсовете", fetchingRates = "Зарежда...",
    ratesFetched = "✓ Курсовете са обновени", ratesFailed = "Неуспешно зареждане",
)

// ── Helper: blank strings instance for unimplemented languages ────
private val blankDayLabels   = List(7) { "" }
private val blankMonthLabels = List(12) { "" }
private fun blankStrings(hoursA: String = "h", minA: String = "min") = AppStrings(
    navRide = "", navStats = "", navSettings = "", navMore = "",
    shiftNoneTitle = "", shiftNoneWarning = "", shiftStartBtn = "",
    shiftActiveLabel = "Shift #%d", shiftEndBtn = "",
    hoursAbbr = hoursA, minAbbr = minA,
    currentFare = "", statusWaiting = "", statusDriving = "", inclAdjustment = "",
    waitLabel = "", secondsMin = "", speedLabel = "", distanceLabel = "",
    fareAdjTitle = "", resetBtn = "", fareAdjHint = "", tariffLabel = "",
    startGpsRide = "", pauseBtn = "", resumeBtn = "", endBtn = "",
    endOfRide = "", rideSummary = "", distanceField = "", durationField = "",
    waitTimeField = "", paymentMethod = "", cash = "", card = "",
    tipLabel = "", saveBtn = "", cancelBtn = "",
    noTariffTitle = "", noTariffMsg = "",
    noShiftDialogTitle = "", noShiftDialogMsg = "", yesContinue = "", noGoBack = "",
    goodDay = "", todayLabel = "", ridesLabel = "", monthlyRevenue = "",
    avgRide = "", perRide = "", tipsToday = "", received = "",
    netProfit = "", afterCosts = "", recentRides = "", noRidesYet = "",
    ridePrefix = "#", tipBadge = "",
    statistics = "", weekLabel = "", monthLabel = "", allLabel = "",
    totalRevenue = "", totalKm = "", avgPerHour = "", avgShift = "",
    traveled = "", revenuePerHour = "", shiftsLabel = "", noShiftSub = "",
    choosePeriod = "", noData = "",
    trendsTitle = "", byDay = "", byHour = "", byMonth = "",
    revenueByDow = "", rideCountByDay = "", revenueByHour = "",
    bestHourColon = "", revenueByMonth = "",
    kpiTitle = "", revenuePerKm = "", totalTips = "", totalWaitKpi = "",
    workTime = "", bestDay = "", peakHour = "", rideCount = "",
    efficiencyTitle = "", timeWithClient = "", waitEfficiency = "",
    topRoutesTitle = "", timesLabel = "",
    breakdownTitle = "", grossRevenue = "", fuelBreakdown = "", taxBreakdown = "",
    dayLabels = blankDayLabels, monthLabels = blankMonthLabels,
    settingsTitle = "", languageSection = "🌐", languageComingSoon = "",
    currencySection = "💱", exchangeRatesNote = "",
    distanceSection = "📍", kilometres = "", miles = "",
    tariffsSection = "📋", noTariffs = "", manualLabel = "", autoLabel = "", addTariff = "",
    expensesSection = "💸", taxInsurance = "", fuelPer = "",
    gpsSection = "📡", waitThreshold = "", waitThresholdHint = "",
    updateInterval = "", updateIntervalHint = "",
    advancedSection = "⚙️", advancedSectionSub = "", costsLabel = "",
    profitPreviewTitle = "", profitPreviewNoTariff = "", profitPreviewSub = "",
    fuelLabel = "",
    shift8hTitle = "", shift8hAvgPerHour = "", shift8hGross = "", shift8hNet = "",
    notEnoughDataLabel = "", notEnoughDataSub = "", per100GrossTitle = "",
    saveChanges = "", newTariff = "", editTariffLabel = "",
    tariffName = "", nameRequired = "", pricingLabel = "",
    startFeeLabel = "", perMinWait = "", hourlyRateLabel = "",
    autoActivate = "", autoActivateSub = "",
    fromLabel = "", toLabel = "", saveLabel = "",
    historyTitle = "", showLabel = "", noRides = "", noRoute = "",
    startMarker = "", endMarker = "",
    moreTitle = "", moreSub = "",
    rideHistoryTitle = "", rideHistorySub = "",
    shiftHistoryTitle = "", shiftHistorySub = "",
    calculatorLabel = "", calculatorSub = "",
    mapLabel = "", mapSub = "",
    shiftHistoryScreen = "", shiftsRecorded = "%d", noShifts = "",
    shiftNum = "#%d", activeLabel = "", avgRideLabel = "", tipsLabel = "",
    waitLabelShort = "", profitLabel = "", noRidesInShift = "", tipBadgeShort = "",
    shiftCompleted = "#%d", ridesCompleted = "", completedLabel = "",
    kilometersLabel = "", withClients = "", avgRidePerRide = "",
    totalWaitLabel = "", noMovement = "",
    financialBreakdown = "", ridesInShift = "", doneBtn = "",
    refreshRates = "🔄", fetchingRates = "...", ratesFetched = "✓", ratesFailed = "✗",
    defaultLabel = "", fromPointLabel = "", toPointLabel = "",
    swapLabel = "", calculating = "", calculateRoutes = "",
    timeLabel = "", totalLabel = "", savedAsRide = "", saveAsRide = "",
    secAbbr = "s", perKmLabel = "/km", perMinLabel = "/min",
    myLocationLabel = "", enterFromTo = "", noRouteFound = "",
    addressNotFound = "", directionsApiError = "", networkError = "",
    routesSingle = "", routesPlural = "", waitSuffix = "",
)

// ── Unimplemented languages (fill in yourself) ────────────────────
val EsStrings = blankStrings()   // Español
val DeStrings = blankStrings()   // Deutsch
val FrStrings = blankStrings()   // Français
val RuStrings = blankStrings()   // Русский
val PtStrings = blankStrings()   // Português
val ZhStrings = blankStrings()   // 中文（简体）
val JaStrings = blankStrings()   // 日本語
val ArStrings = blankStrings()   // العربية

val LocalStrings  = compositionLocalOf { EnStrings }
val LocalSettings = compositionLocalOf { AppSettings() }
