package com.taxipro.ui.theme

import androidx.compose.runtime.compositionLocalOf
import com.taxipro.data.db.AppSettings

data class AppStrings(
    // Navigation
    val navRide: String,
    val navStats: String,
    val navSettings: String,
    val navMore: String,
    // Shift banner
    val shiftNoneTitle: String,
    val shiftNoneWarning: String,
    val shiftStartBtn: String,
    val shiftActiveLabel: String,
    val shiftEndBtn: String,
    // Active ride - fare card
    val currentFare: String,
    val statusWaiting: String,
    val statusDriving: String,
    val inclAdjustment: String,
    // Metric cards
    val waitLabel: String,
    val secondsMin: String,
    val speedLabel: String,
    val distanceLabel: String,
    // Fare adjustment
    val fareAdjTitle: String,
    val resetBtn: String,
    val fareAdjHint: String,
    // Tariff
    val tariffLabel: String,
    // Start button
    val startGpsRide: String,
    // Controls
    val pauseBtn: String,
    val resumeBtn: String,
    val endBtn: String,
    // End ride dialog
    val endOfRide: String,
    val rideSummary: String,
    val distanceField: String,
    val durationField: String,
    val waitTimeField: String,
    val paymentMethod: String,
    val cash: String,
    val card: String,
    val tipLabel: String,
    val saveBtn: String,
    val cancelBtn: String,
    // No tariff
    val noTariffTitle: String,
    val noTariffMsg: String,
    // No shift dialog
    val noShiftDialogTitle: String,
    val noShiftDialogMsg: String,
    val yesContinue: String,
    val noGoBack: String,
    // Dashboard
    val goodDay: String,
    val todayLabel: String,
    val ridesLabel: String,
    val monthlyRevenue: String,
    val avgRide: String,
    val perRide: String,
    val tipsToday: String,
    val received: String,
    val netProfit: String,
    val afterCosts: String,
    val recentRides: String,
    val noRidesYet: String,
    val ridePrefix: String,
    val tipBadge: String,
    // Statistics
    val statistics: String,
    val weekLabel: String,
    val monthLabel: String,
    val allLabel: String,
    val totalRevenue: String,
    val totalKm: String,
    val avgPerHour: String,
    val avgShift: String,
    val traveled: String,
    val revenuePerHour: String,
    val shiftsLabel: String,
    val noShiftSub: String,
    val choosePeriod: String,
    val noData: String,
    val trendsTitle: String,
    val byDay: String,
    val byHour: String,
    val byMonth: String,
    val revenueByDow: String,
    val rideCountByDay: String,
    val revenueByHour: String,
    val bestHourColon: String,
    val revenueByMonth: String,
    val kpiTitle: String,
    val revenuePerKm: String,
    val totalTips: String,
    val totalWaitKpi: String,
    val workTime: String,
    val bestDay: String,
    val peakHour: String,
    val rideCount: String,
    val efficiencyTitle: String,
    val timeWithClient: String,
    val waitEfficiency: String,
    val topRoutesTitle: String,
    val timesLabel: String,
    val breakdownTitle: String,
    val grossRevenue: String,
    val fuelBreakdown: String,
    val taxBreakdown: String,
    val dayLabels: List<String>,
    val monthLabels: List<String>,
    // Settings
    val settingsTitle: String,
    val languageSection: String,
    val languageComingSoon: String,
    val currencySection: String,
    val exchangeRatesNote: String,
    val distanceSection: String,
    val kilometres: String,
    val miles: String,
    val tariffsSection: String,
    val noTariffs: String,
    val manualLabel: String,
    val autoLabel: String,
    val addTariff: String,
    val expensesSection: String,
    val taxInsurance: String,
    val fuelPer: String,
    val gpsSection: String,
    val waitThreshold: String,
    val waitThresholdHint: String,
    val updateInterval: String,
    val updateIntervalHint: String,
    val saveChanges: String,
    val newTariff: String,
    val editTariffLabel: String,
    val tariffName: String,
    val nameRequired: String,
    val pricingLabel: String,
    val startFeeLabel: String,
    val perMinWait: String,
    val hourlyRateLabel: String,
    val autoActivate: String,
    val autoActivateSub: String,
    val fromLabel: String,
    val toLabel: String,
    val saveLabel: String,
    // History
    val historyTitle: String,
    val showLabel: String,
    val noRides: String,
    val noRoute: String,
    val startMarker: String,
    val endMarker: String,
    // More menu
    val moreTitle: String,
    val moreSub: String,
    val rideHistoryTitle: String,
    val rideHistorySub: String,
    val shiftHistoryTitle: String,
    val shiftHistorySub: String,
    val calculatorLabel: String,
    val calculatorSub: String,
    val mapLabel: String,
    val mapSub: String,
    // Shift history
    val shiftHistoryScreen: String,
    val shiftsRecorded: String,
    val noShifts: String,
    val shiftNum: String,
    val activeLabel: String,
    val avgRideLabel: String,
    val tipsLabel: String,
    val waitLabelShort: String,
    val profitLabel: String,
    val noRidesInShift: String,
    val tipBadgeShort: String,
    // Shift summary
    val shiftCompleted: String,
    val ridesCompleted: String,
    val completedLabel: String,
    val kilometersLabel: String,
    val withClients: String,
    val avgRidePerRide: String,
    val totalWaitLabel: String,
    val noMovement: String,
    val financialBreakdown: String,
    val ridesInShift: String,
    val doneBtn: String,
)

val EnStrings = AppStrings(
    navRide = "Ride", navStats = "Stats", navSettings = "Settings", navMore = "More",
    shiftNoneTitle = "No active shift",
    shiftNoneWarning = "Tracking shifts helps you see daily earnings, compare performance and keep accurate records.",
    shiftStartBtn = "Start shift",
    shiftActiveLabel = "Shift #%d active",
    shiftEndBtn = "End shift",
    currentFare = "CURRENT FARE",
    statusWaiting = "⏸  WAITING",
    statusDriving = "▶  DRIVING",
    inclAdjustment = "incl. adjustment",
    waitLabel = "WAIT", secondsMin = "seconds / min", speedLabel = "SPEED", distanceLabel = "DISTANCE",
    fareAdjTitle = "FARE ADJUSTMENT", resetBtn = "Reset",
    fareAdjHint = "Tap to add or remove from the fare (not a tip)",
    tariffLabel = "TARIFF",
    startGpsRide = "START GPS RIDE",
    pauseBtn = "Pause", resumeBtn = "Resume", endBtn = "END",
    endOfRide = "End of ride", rideSummary = "RIDE SUMMARY",
    distanceField = "Distance", durationField = "Duration", waitTimeField = "Wait time",
    paymentMethod = "Payment method", cash = "💵 Cash", card = "💳 Card",
    tipLabel = "Tip", saveBtn = "SAVE", cancelBtn = "Cancel",
    noTariffTitle = "No tariff selected",
    noTariffMsg = "Please add a tariff in Settings before starting a ride.",
    noShiftDialogTitle = "No active shift",
    noShiftDialogMsg = "You have no active shift. The ride will be saved in overall statistics but will not count towards a shift.\n\nDo you want to continue?",
    yesContinue = "Yes, continue", noGoBack = "No, go back",
    goodDay = "Good day, driver! 🚕",
    todayLabel = "Today", ridesLabel = "Rides", monthlyRevenue = "Monthly revenue",
    avgRide = "Avg ride", perRide = "per ride", tipsToday = "Tips today",
    received = "received", netProfit = "Net profit", afterCosts = "after costs",
    recentRides = "Recent rides",
    noRidesYet = "No rides yet.\nTap 'Ride' to start!",
    ridePrefix = "Ride #", tipBadge = "tip",
    statistics = "Statistics", weekLabel = "Week", monthLabel = "Month", allLabel = "All",
    totalRevenue = "Total revenue", totalKm = "Total km",
    avgPerHour = "Avg/hour", avgShift = "Avg shift",
    traveled = "traveled", revenuePerHour = "revenue/hour",
    shiftsLabel = "shifts", noShiftSub = "no shift",
    choosePeriod = "Choose period", noData = "No data for the selected period.",
    trendsTitle = "📈 Trends", byDay = "By day", byHour = "By hour", byMonth = "By month",
    revenueByDow = "Revenue by day of week", rideCountByDay = "Ride count by day",
    revenueByHour = "Revenue by hour of day", bestHourColon = "Best hour:",
    revenueByMonth = "Revenue by month",
    kpiTitle = "📊 Key indicators", revenuePerKm = "Revenue per km",
    totalTips = "Total tips", totalWaitKpi = "Total wait", workTime = "Work time",
    bestDay = "Best day", peakHour = "Peak hour", rideCount = "Ride count",
    efficiencyTitle = "⚡ Efficiency", timeWithClient = "Time with client",
    waitEfficiency = "Wait time", topRoutesTitle = "🗺 Top routes", timesLabel = "times",
    breakdownTitle = "💸 Breakdown (approx.)", grossRevenue = "Gross revenue",
    fuelBreakdown = "Fuel (~0.18/km)", taxBreakdown = "Tax (15%)",
    dayLabels = listOf("Mon","Tue","Wed","Thu","Fri","Sat","Sun"),
    monthLabels = listOf("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"),
    settingsTitle = "Settings", languageSection = "🌐  Language",
    languageComingSoon = "Coming soon",
    currencySection = "💱  Currency",
    exchangeRatesNote = "Exchange rates vs EUR  (update manually every 2 weeks)",
    distanceSection = "📍  Distance unit", kilometres = "Kilometres", miles = "Miles",
    tariffsSection = "📋  Tariffs", noTariffs = "No tariffs yet.",
    manualLabel = "Manual", autoLabel = "Auto", addTariff = "Add Tariff",
    expensesSection = "💸  Expenses", taxInsurance = "Tax & insurance", fuelPer = "Fuel per",
    gpsSection = "📡  GPS", waitThreshold = "Wait threshold",
    waitThresholdHint = "Speed below which wait time is counted",
    updateInterval = "Update interval",
    updateIntervalHint = "Min 1000ms (Android limit). 1000 = max precision",
    saveChanges = "Save Changes", newTariff = "New Tariff", editTariffLabel = "Edit Tariff",
    tariffName = "Tariff name", nameRequired = "Name is required",
    pricingLabel = "PRICING", startFeeLabel = "Start fee", perMinWait = "Per min wait",
    hourlyRateLabel = "Hourly rate", autoActivate = "Auto-activate",
    autoActivateSub = "Switches on at a specific hour",
    fromLabel = "From", toLabel = "To", saveLabel = "Save",
    historyTitle = "History", showLabel = "Show:", noRides = "No rides for the selected period.",
    noRoute = "No route recorded for this ride.", startMarker = "Start", endMarker = "End",
    moreTitle = "More", moreSub = "Additional features",
    rideHistoryTitle = "Ride History", rideHistorySub = "View all rides",
    shiftHistoryTitle = "Shift History", shiftHistorySub = "View by work shifts",
    calculatorLabel = "Calculator", calculatorSub = "Calculate fare by route",
    mapLabel = "Map", mapSub = "Current position and route",
    shiftHistoryScreen = "Shift History", shiftsRecorded = "%d shifts recorded",
    noShifts = "No completed shifts yet.", shiftNum = "Shift #%d", activeLabel = "ACTIVE",
    avgRideLabel = "Avg ride", tipsLabel = "Tips", waitLabelShort = "Wait",
    profitLabel = "Profit", noRidesInShift = "No rides in this shift.", tipBadgeShort = "tip",
    shiftCompleted = "Shift #%d complete", ridesCompleted = "Rides", completedLabel = "completed",
    kilometersLabel = "Kilometres", withClients = "with clients", avgRidePerRide = "per ride",
    totalWaitLabel = "Total wait", noMovement = "no movement",
    financialBreakdown = "💸 Financial breakdown", ridesInShift = "🚖 Rides in this shift",
    doneBtn = "Done",
)

val BgStrings = AppStrings(
    navRide = "Курс", navStats = "Статист.", navSettings = "Настройки", navMore = "Още",
    shiftNoneTitle = "Няма активна смяна",
    shiftNoneWarning = "Проследяването на смени ви помага да виждате приходите за работен ден, да сравнявате представянето си и да водите точни записи.",
    shiftStartBtn = "Започни смяна",
    shiftActiveLabel = "Смяна #%d активна",
    shiftEndBtn = "Приключи",
    currentFare = "ТЕКУЩА ЦЕНА",
    statusWaiting = "⏸  ИЗЧАКВАНЕ",
    statusDriving = "▶  ШОФИРАНЕ",
    inclAdjustment = "вкл. корекция",
    waitLabel = "ПРЕСТОЙ", secondsMin = "секунди / мин", speedLabel = "СКОРОСТ", distanceLabel = "РАЗСТОЯНИЕ",
    fareAdjTitle = "КОРЕКЦИЯ НА ЦЕНА", resetBtn = "Нулиране",
    fareAdjHint = "Натисни за добавяне или премахване от цената (не е бакшиш)",
    tariffLabel = "ТАРИФА",
    startGpsRide = "СТАРТИРАЙ GPS КУРС",
    pauseBtn = "Пауза", resumeBtn = "Продължи", endBtn = "КРАЙ",
    endOfRide = "Край на курс", rideSummary = "ОБОБЩЕНИЕ НА КУРС",
    distanceField = "Разстояние", durationField = "Продължителност", waitTimeField = "Престой",
    paymentMethod = "Начин на плащане", cash = "💵 В брой", card = "💳 Карта",
    tipLabel = "Бакшиш", saveBtn = "ЗАПАЗИ", cancelBtn = "Отказ",
    noTariffTitle = "Нямате избрана тарифа",
    noTariffMsg = "Моля добавете тарифа в Настройки преди да започнете курс.",
    noShiftDialogTitle = "Няма активна смяна",
    noShiftDialogMsg = "Нямате активна смяна. Курсът ще бъде записан в общата статистика, но няма да се счита към смяна.\n\nИскате ли да продължите?",
    yesContinue = "Да, продължи", noGoBack = "Не, върни се",
    goodDay = "Добър ден, шофьор! 🚕",
    todayLabel = "Днес", ridesLabel = "Курса", monthlyRevenue = "Месечен приход",
    avgRide = "Среден курс", perRide = "за курс", tipsToday = "Бакшиши днес",
    received = "получени", netProfit = "Чиста печалба", afterCosts = "след разходи",
    recentRides = "Последни курсове",
    noRidesYet = "Все още няма курсове.\nНатисни 'Курс' за да започнеш!",
    ridePrefix = "Курс #", tipBadge = "бакш.",
    statistics = "Статистики", weekLabel = "Седмица", monthLabel = "Месец", allLabel = "Всички",
    totalRevenue = "Общо приходи", totalKm = "Общо км",
    avgPerHour = "Сред. на час", avgShift = "Сред. смяна",
    traveled = "изминати", revenuePerHour = "приход/час",
    shiftsLabel = "смени", noShiftSub = "без смяна",
    choosePeriod = "Избери период", noData = "Няма данни за избрания период.",
    trendsTitle = "📈 Тенденции", byDay = "По ден", byHour = "По час", byMonth = "По месец",
    revenueByDow = "Приход по ден от седмицата", rideCountByDay = "Брой курсове по ден",
    revenueByHour = "Приход по час от деня", bestHourColon = "Най-добър час:",
    revenueByMonth = "Приход по месец",
    kpiTitle = "📊 Ключови показатели", revenuePerKm = "Приход на км",
    totalTips = "Общо бакшиши", totalWaitKpi = "Общо престой", workTime = "Работно време",
    bestDay = "Най-добър ден", peakHour = "Пик час", rideCount = "Брой курсове",
    efficiencyTitle = "⚡ Ефективност", timeWithClient = "Време с клиент",
    waitEfficiency = "Престой", topRoutesTitle = "🗺 Топ маршрути", timesLabel = "пъти",
    breakdownTitle = "💸 Разбивка (приблизителна)", grossRevenue = "Брутен приход",
    fuelBreakdown = "Гориво (~0.18/км)", taxBreakdown = "Данъци (15%)",
    dayLabels = listOf("Пн","Вт","Ср","Чт","Пт","Сб","Нд"),
    monthLabels = listOf("Ян","Фев","Мар","Апр","Май","Юн","Юл","Авг","Сеп","Окт","Ное","Дек"),
    settingsTitle = "Настройки", languageSection = "🌐  Език",
    languageComingSoon = "Очаквайте скоро",
    currencySection = "💱  Валута",
    exchangeRatesNote = "Обменни курсове спрямо EUR (актуализирайте ръчно на всеки 2 седмици)",
    distanceSection = "📍  Мерна единица", kilometres = "Километри", miles = "Мили",
    tariffsSection = "📋  Тарифи", noTariffs = "Все още няма тарифи.",
    manualLabel = "Ръчна", autoLabel = "Авто", addTariff = "Добави тарифа",
    expensesSection = "💸  Разходи", taxInsurance = "Данъци и застраховки", fuelPer = "Гориво на",
    gpsSection = "📡  GPS", waitThreshold = "Праг на изчакване",
    waitThresholdHint = "Скорост, под която се отчита престой",
    updateInterval = "Интервал на обновяване",
    updateIntervalHint = "Мин 1000мс (лимит на Android). 1000 = макс точност",
    saveChanges = "Запази промените", newTariff = "Нова тарифа", editTariffLabel = "Редактирай тарифа",
    tariffName = "Ime на тарифата", nameRequired = "Името е задължително",
    pricingLabel = "ЦЕНООБРАЗУВАНЕ", startFeeLabel = "Начална такса", perMinWait = "На мин престой",
    hourlyRateLabel = "Почасова ставка", autoActivate = "Авто-активиране",
    autoActivateSub = "Включва се в определен час",
    fromLabel = "От", toLabel = "До", saveLabel = "Запази",
    historyTitle = "История", showLabel = "Покажи:", noRides = "Няма курсове за избрания период.",
    noRoute = "Няма запазен маршрут за този курс.", startMarker = "Начало", endMarker = "Край",
    moreTitle = "Още", moreSub = "Допълнителни функции",
    rideHistoryTitle = "История на курсове", rideHistorySub = "Преглед на всички курсове",
    shiftHistoryTitle = "История на смени", shiftHistorySub = "Преглед по работни смени",
    calculatorLabel = "Калкулатор", calculatorSub = "Изчисли цена по маршрут",
    mapLabel = "Карта", mapSub = "Текуща позиция и маршрут",
    shiftHistoryScreen = "История на смени", shiftsRecorded = "%d смени записани",
    noShifts = "Все още няма завършени смени.", shiftNum = "Смяна #%d", activeLabel = "АКТИВНА",
    avgRideLabel = "Среден курс", tipsLabel = "Бакшиши", waitLabelShort = "Престой",
    profitLabel = "Печалба", noRidesInShift = "Няма курсове в тази смяна.", tipBadgeShort = "бакш.",
    shiftCompleted = "Смяна #%d завърши", ridesCompleted = "Курсове", completedLabel = "завършени",
    kilometersLabel = "Километри", withClients = "с клиенти", avgRidePerRide = "на курс",
    totalWaitLabel = "Общо престой", noMovement = "без движение",
    financialBreakdown = "💸 Финансова разбивка", ridesInShift = "🚖 Курсове в тази смяна",
    doneBtn = "Готово",
)

val LocalStrings = compositionLocalOf { EnStrings }
val LocalSettings = compositionLocalOf { AppSettings() }
